<?php
/**
 * Copyright © Smartex Canada All rights reserved.
 * See LICENSE for license details.
 */
?>
<?php
/**
 * @var \Magento\Swatches\Block\Product\Renderer\Listing\Configurable $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Swatches\ViewModel\Product\Renderer\Configurable $configurableViewModel
 */
$configurableViewModel = $block->getConfigurableViewModel();
$productId = $block->getProduct()->getId();

$showCount = $configurableViewModel->getShowSwatchCount();
?>
<div class="swatch-opt-<?= $escaper->escapeHtmlAttr($productId) ?><?= $escaper->escapeHtmlAttr(($showCount) ? ' swatch-count' : '') ?>"
     data-role="swatch-option-<?= $escaper->escapeHtmlAttr($productId) ?>"></div>

<?php if ($showCount) : ?>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= $escaper->escapeJs($productId) ?>]": {
            "Smartex_SwatchesCount/js/swatch-count-renderer": {
                "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>
            }
        }
    }
</script>
<?php else: ?>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= $escaper->escapeJs($productId) ?>]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".product-item-details",
                "onlySwatches": true,
                "enableControlLabel": false,
                "numberToShow": <?=  $escaper->escapeJs($block->getNumberSwatchesPerProduct()) ?>,
                "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getMediaCallback())) ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $escaper->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $escaper->escapeJs($productId) ?>]": {
            "priceBox": {
                "priceConfig": {
                    "priceFormat": <?= /* @noEscape */ $block->getPriceFormatJson(); ?>,
                    "prices": <?= /* @noEscape */ $block->getPricesJson(); ?>
                }
            }
        }
    }
</script>
<?php endif; ?>
